package sliang.vocalbularybook;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sliang.vacalbularybook.Explain;
import sliang.vacalbularybook.Translations;
import sliang.vacalbularybook.Word;

import sliang.vocalbularybook.ExplainDao;
import sliang.vocalbularybook.TranslationsDao;
import sliang.vocalbularybook.WordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig explainDaoConfig;
    private final DaoConfig translationsDaoConfig;
    private final DaoConfig wordDaoConfig;

    private final ExplainDao explainDao;
    private final TranslationsDao translationsDao;
    private final WordDao wordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        explainDaoConfig = daoConfigMap.get(ExplainDao.class).clone();
        explainDaoConfig.initIdentityScope(type);

        translationsDaoConfig = daoConfigMap.get(TranslationsDao.class).clone();
        translationsDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        explainDao = new ExplainDao(explainDaoConfig, this);
        translationsDao = new TranslationsDao(translationsDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);

        registerDao(Explain.class, explainDao);
        registerDao(Translations.class, translationsDao);
        registerDao(Word.class, wordDao);
    }
    
    public void clear() {
        explainDaoConfig.clearIdentityScope();
        translationsDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
    }

    public ExplainDao getExplainDao() {
        return explainDao;
    }

    public TranslationsDao getTranslationsDao() {
        return translationsDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

}
