package sliang.vocalbularybook;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sliang.vacalbularybook.Explain;
import sliang.vacalbularybook.Translations;
import sliang.vacalbularybook.Word;
import sliang.vacalbularybook.WordVoice;
import sliang.vacalbularybook.StrangeWordBook;

import sliang.vocalbularybook.ExplainDao;
import sliang.vocalbularybook.TranslationsDao;
import sliang.vocalbularybook.WordDao;
import sliang.vocalbularybook.WordVoiceDao;
import sliang.vocalbularybook.StrangeWordBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig explainDaoConfig;
    private final DaoConfig translationsDaoConfig;
    private final DaoConfig wordDaoConfig;
    private final DaoConfig wordVoiceDaoConfig;
    private final DaoConfig strangeWordBookDaoConfig;

    private final ExplainDao explainDao;
    private final TranslationsDao translationsDao;
    private final WordDao wordDao;
    private final WordVoiceDao wordVoiceDao;
    private final StrangeWordBookDao strangeWordBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        explainDaoConfig = daoConfigMap.get(ExplainDao.class).clone();
        explainDaoConfig.initIdentityScope(type);

        translationsDaoConfig = daoConfigMap.get(TranslationsDao.class).clone();
        translationsDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        wordVoiceDaoConfig = daoConfigMap.get(WordVoiceDao.class).clone();
        wordVoiceDaoConfig.initIdentityScope(type);

        strangeWordBookDaoConfig = daoConfigMap.get(StrangeWordBookDao.class).clone();
        strangeWordBookDaoConfig.initIdentityScope(type);

        explainDao = new ExplainDao(explainDaoConfig, this);
        translationsDao = new TranslationsDao(translationsDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);
        wordVoiceDao = new WordVoiceDao(wordVoiceDaoConfig, this);
        strangeWordBookDao = new StrangeWordBookDao(strangeWordBookDaoConfig, this);

        registerDao(Explain.class, explainDao);
        registerDao(Translations.class, translationsDao);
        registerDao(Word.class, wordDao);
        registerDao(WordVoice.class, wordVoiceDao);
        registerDao(StrangeWordBook.class, strangeWordBookDao);
    }
    
    public void clear() {
        explainDaoConfig.clearIdentityScope();
        translationsDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
        wordVoiceDaoConfig.clearIdentityScope();
        strangeWordBookDaoConfig.clearIdentityScope();
    }

    public ExplainDao getExplainDao() {
        return explainDao;
    }

    public TranslationsDao getTranslationsDao() {
        return translationsDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public WordVoiceDao getWordVoiceDao() {
        return wordVoiceDao;
    }

    public StrangeWordBookDao getStrangeWordBookDao() {
        return strangeWordBookDao;
    }

}
