package sliang.vocalbularybook;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import sliang.vacalbularybook.Word;

import sliang.vacalbularybook.StrangeWordBook;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STRANGE_WORD_BOOK".
*/
public class StrangeWordBookDao extends AbstractDao<StrangeWordBook, Long> {

    public static final String TABLENAME = "STRANGE_WORD_BOOK";

    /**
     * Properties of entity StrangeWordBook.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StrangeWordBookId = new Property(0, long.class, "strangeWordBookId", true, "_id");
        public final static Property DataTime = new Property(1, long.class, "dataTime", false, "DATA_TIME");
        public final static Property ClickNum = new Property(2, int.class, "clickNum", false, "CLICK_NUM");
        public final static Property WordId = new Property(3, long.class, "wordId", false, "WORD_ID");
    }

    private DaoSession daoSession;


    public StrangeWordBookDao(DaoConfig config) {
        super(config);
    }
    
    public StrangeWordBookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STRANGE_WORD_BOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: strangeWordBookId
                "\"DATA_TIME\" INTEGER NOT NULL ," + // 1: dataTime
                "\"CLICK_NUM\" INTEGER NOT NULL ," + // 2: clickNum
                "\"WORD_ID\" INTEGER NOT NULL );"); // 3: wordId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STRANGE_WORD_BOOK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StrangeWordBook entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStrangeWordBookId());
        stmt.bindLong(2, entity.getDataTime());
        stmt.bindLong(3, entity.getClickNum());
        stmt.bindLong(4, entity.getWordId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StrangeWordBook entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStrangeWordBookId());
        stmt.bindLong(2, entity.getDataTime());
        stmt.bindLong(3, entity.getClickNum());
        stmt.bindLong(4, entity.getWordId());
    }

    @Override
    protected final void attachEntity(StrangeWordBook entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public StrangeWordBook readEntity(Cursor cursor, int offset) {
        StrangeWordBook entity = new StrangeWordBook( //
            cursor.getLong(offset + 0), // strangeWordBookId
            cursor.getLong(offset + 1), // dataTime
            cursor.getInt(offset + 2), // clickNum
            cursor.getLong(offset + 3) // wordId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StrangeWordBook entity, int offset) {
        entity.setStrangeWordBookId(cursor.getLong(offset + 0));
        entity.setDataTime(cursor.getLong(offset + 1));
        entity.setClickNum(cursor.getInt(offset + 2));
        entity.setWordId(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StrangeWordBook entity, long rowId) {
        entity.setStrangeWordBookId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StrangeWordBook entity) {
        if(entity != null) {
            return entity.getStrangeWordBookId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StrangeWordBook entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWordDao().getAllColumns());
            builder.append(" FROM STRANGE_WORD_BOOK T");
            builder.append(" LEFT JOIN WORD T0 ON T.\"WORD_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected StrangeWordBook loadCurrentDeep(Cursor cursor, boolean lock) {
        StrangeWordBook entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Word word = loadCurrentOther(daoSession.getWordDao(), cursor, offset);
         if(word != null) {
            entity.setWord(word);
        }

        return entity;    
    }

    public StrangeWordBook loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<StrangeWordBook> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<StrangeWordBook> list = new ArrayList<StrangeWordBook>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<StrangeWordBook> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<StrangeWordBook> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
