package sliang.vocalbularybook;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import sliang.vacalbularybook.Translations;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSLATIONS".
*/
public class TranslationsDao extends AbstractDao<Translations, Void> {

    public static final String TABLENAME = "TRANSLATIONS";

    /**
     * Properties of entity Translations.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property WordId = new Property(0, long.class, "wordId", false, "WORD_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    }


    public TranslationsDao(DaoConfig config) {
        super(config);
    }
    
    public TranslationsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSLATIONS\" (" + //
                "\"WORD_ID\" INTEGER NOT NULL ," + // 0: wordId
                "\"NAME\" TEXT);"); // 1: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSLATIONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Translations entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getWordId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Translations entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getWordId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Translations readEntity(Cursor cursor, int offset) {
        Translations entity = new Translations( //
            cursor.getLong(offset + 0), // wordId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Translations entity, int offset) {
        entity.setWordId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Translations entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Translations entity) {
        return null;
    }

    @Override
    public boolean hasKey(Translations entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
