package sliang.vocalbularybook;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import sliang.vacalbularybook.Word;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WORD".
*/
public class WordDao extends AbstractDao<Word, Long> {

    public static final String TABLENAME = "WORD";

    /**
     * Properties of entity Word.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property UsPhonetic = new Property(2, String.class, "usPhonetic", false, "US_PHONETIC");
        public final static Property Phonetic = new Property(3, String.class, "phonetic", false, "PHONETIC");
        public final static Property UkPhonetic = new Property(4, String.class, "ukPhonetic", false, "UK_PHONETIC");
    }

    private DaoSession daoSession;


    public WordDao(DaoConfig config) {
        super(config);
    }
    
    public WordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"US_PHONETIC\" TEXT," + // 2: usPhonetic
                "\"PHONETIC\" TEXT," + // 3: phonetic
                "\"UK_PHONETIC\" TEXT);"); // 4: ukPhonetic
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Word entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String usPhonetic = entity.getUsPhonetic();
        if (usPhonetic != null) {
            stmt.bindString(3, usPhonetic);
        }
 
        String phonetic = entity.getPhonetic();
        if (phonetic != null) {
            stmt.bindString(4, phonetic);
        }
 
        String ukPhonetic = entity.getUkPhonetic();
        if (ukPhonetic != null) {
            stmt.bindString(5, ukPhonetic);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Word entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String usPhonetic = entity.getUsPhonetic();
        if (usPhonetic != null) {
            stmt.bindString(3, usPhonetic);
        }
 
        String phonetic = entity.getPhonetic();
        if (phonetic != null) {
            stmt.bindString(4, phonetic);
        }
 
        String ukPhonetic = entity.getUkPhonetic();
        if (ukPhonetic != null) {
            stmt.bindString(5, ukPhonetic);
        }
    }

    @Override
    protected final void attachEntity(Word entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Word readEntity(Cursor cursor, int offset) {
        Word entity = new Word( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // usPhonetic
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // phonetic
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // ukPhonetic
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Word entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUsPhonetic(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhonetic(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUkPhonetic(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Word entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Word entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Word entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
